INSERT INTO CAR_TYPE (TYPE_ID,BRAND, MODEL, SEATS, TRANSMISSION_TYPE, TRUNK_VOLUME, PRICE) VALUES (20,'Honda', 'RS', 4, 'full', 45, 20);
INSERT INTO CAR_TYPE (TYPE_ID,BRAND, MODEL, SEATS, TRANSMISSION_TYPE, TRUNK_VOLUME, PRICE) VALUES (21,'Mazda', 'RH', 4, 'full', 42, 30);
INSERT INTO CAR_TYPE (TYPE_ID,BRAND, MODEL, SEATS, TRANSMISSION_TYPE, TRUNK_VOLUME, PRICE) VALUES (22,'Toyota', 'RN', 4, 'full', 49, 30);

INSERT INTO CAR (CAR_ID, ADDRESS, COLOR, NUMBER, ACTIVE, CAR_TYPE) VALUES (30,'Kharkiv','blue','12345',TRUE,20);
INSERT INTO CAR (CAR_ID, ADDRESS, COLOR, NUMBER, ACTIVE, CAR_TYPE) VALUES (31,'Kharkiv','green','12456',TRUE,20);
INSERT INTO CAR (CAR_ID, ADDRESS, COLOR, NUMBER, ACTIVE, CAR_TYPE) VALUES (32,'Kiev','red','12367',TRUE,21);

INSERT INTO USER (USER_ID, BIRTH_DATE, LICENSE, MAIL, NAME, PASSWORD, SURNAME, NUMBER) VALUES (40,'1993-12-26','456','daric@mail.ru','Daria','111','Koreneva','0963687818')