INSERT INTO CAR_TYPE (TYPE_ID,BRAND, MODEL, SEATS, TRANSMISSION_TYPE, TRUNK_VOLUME) VALUES (20,'Honda', 'RS', 4, 'full', 45);
INSERT INTO CAR_TYPE (TYPE_ID,BRAND, MODEL, SEATS, TRANSMISSION_TYPE, TRUNK_VOLUME) VALUES (21,'Mazda', 'RH', 4, 'full', 42);
INSERT INTO CAR_TYPE (TYPE_ID,BRAND, MODEL, SEATS, TRANSMISSION_TYPE, TRUNK_VOLUME) VALUES (22,'Toyota', 'RN', 4, 'full', 49);